### ISSUE TITLE
Customizing model card fields

### ISSUE THREAD

**Issue by smrnvdhy** [tensorflow/model-card-toolkit#212] opened 2022-05-13 21:14 UTC
Thank you for your amazing work on the model card! I'm wondering how I can go about customizing the model card fields. In particular, I'm interested in adding my own fields (For example, a custom trust score, whether this model has passed the review board, etc.) in a new section of the model card.

If the fields are already there, I could modify the jinja template to create the model card that I want. However, I'm not sure how I can create these new fields myself. Would appreciate your help!

**Comment by Starborn** [comment] 2022-05-14 01:37
Greets, I have already started creating model cards with my own
templates/elemnts
and would like to inherit some code however
all the source files linked on this page, lead to 404 page not found errors
https://www.tensorflow.org/responsible_ai/model_card_toolkit/api_docs/python/model_card_toolkit/BaseModelCardField
can someone share the sources. or mend the page, thank you
give code, will happily replicate
thanks
PDM

**Comment by smrnvdhy** [comment] 2022-05-16 22:48
@Starborn I believe this should contain the information you mentioned: https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/base_model_card_field.py

Could you share an example of how you created your own model card fields?

**Comment by Starborn** [comment] 2022-05-19 03:51
Thank you

this template works, but I dont like to code by hand
Is there a code generator to mint cards?

 regarding MMC, it is still '' on paper''
I simply create  fields and subfields that correspond to categories my
metamodel
I am going to try to use the py template you share but it could well
be implemented using json or other notation,

P

**Comment by bahadirery** [comment] 2022-11-30 17:45
Greetings,

I managed to add custom fields. You have to modify the proto, core.py, model_card.py, and the default template file then build from the source. Check this repo: https://github.com/bahadirery/model-card-toolkit.git

**Comment by codesue** [comment] 2022-12-06 20:01
Hi everyone, thank you for your feedback and suggestions here! I'm going to close this issue as a duplicate of https://github.com/tensorflow/model-card-toolkit/issues/186. Please join in on the discussion in https://github.com/tensorflow/model-card-toolkit/issues/186 or subscribe to it for updates on this work.

The short answer is that right now, creating custom model card fields isn't supported, but we're exploring ways to make this possible.

**Closed** 2022-12-06 20:02 UTC
Labels: duplicate
